/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SurveyComponent {
        "surveyData": any;
    }
}
declare global {
    interface HTMLSurveyComponentElement extends Components.SurveyComponent, HTMLStencilElement {
    }
    var HTMLSurveyComponentElement: {
        prototype: HTMLSurveyComponentElement;
        new (): HTMLSurveyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "survey-component": HTMLSurveyComponentElement;
    }
}
declare namespace LocalJSX {
    interface SurveyComponent {
        "surveyData"?: any;
    }
    interface IntrinsicElements {
        "survey-component": SurveyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "survey-component": LocalJSX.SurveyComponent & JSXBase.HTMLAttributes<HTMLSurveyComponentElement>;
        }
    }
}
