/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RadioQuestionType } from "./utils/types";
export { RadioQuestionType } from "./utils/types";
export namespace Components {
    interface CheckboxQuestion {
        "question": RadioQuestionType;
        "questionNumber": number;
        "updateAnswers": (key: string, value: string[]) => void;
    }
    interface RadioQuestion {
        "question": RadioQuestionType;
        "questionNumber": number;
        "updateAnswers": (key: string, value: string[]) => void;
    }
    interface SurveyComponent {
        "surveyData": any;
    }
    interface TextQuestion {
        "question": any;
        "questionNumber": number;
        "updateAnswers": (key: string, value: string[]) => void;
    }
}
declare global {
    interface HTMLCheckboxQuestionElement extends Components.CheckboxQuestion, HTMLStencilElement {
    }
    var HTMLCheckboxQuestionElement: {
        prototype: HTMLCheckboxQuestionElement;
        new (): HTMLCheckboxQuestionElement;
    };
    interface HTMLRadioQuestionElement extends Components.RadioQuestion, HTMLStencilElement {
    }
    var HTMLRadioQuestionElement: {
        prototype: HTMLRadioQuestionElement;
        new (): HTMLRadioQuestionElement;
    };
    interface HTMLSurveyComponentElement extends Components.SurveyComponent, HTMLStencilElement {
    }
    var HTMLSurveyComponentElement: {
        prototype: HTMLSurveyComponentElement;
        new (): HTMLSurveyComponentElement;
    };
    interface HTMLTextQuestionElement extends Components.TextQuestion, HTMLStencilElement {
    }
    var HTMLTextQuestionElement: {
        prototype: HTMLTextQuestionElement;
        new (): HTMLTextQuestionElement;
    };
    interface HTMLElementTagNameMap {
        "checkbox-question": HTMLCheckboxQuestionElement;
        "radio-question": HTMLRadioQuestionElement;
        "survey-component": HTMLSurveyComponentElement;
        "text-question": HTMLTextQuestionElement;
    }
}
declare namespace LocalJSX {
    interface CheckboxQuestion {
        "question"?: RadioQuestionType;
        "questionNumber"?: number;
        "updateAnswers"?: (key: string, value: string[]) => void;
    }
    interface RadioQuestion {
        "question"?: RadioQuestionType;
        "questionNumber"?: number;
        "updateAnswers"?: (key: string, value: string[]) => void;
    }
    interface SurveyComponent {
        "surveyData"?: any;
    }
    interface TextQuestion {
        "question"?: any;
        "questionNumber"?: number;
        "updateAnswers"?: (key: string, value: string[]) => void;
    }
    interface IntrinsicElements {
        "checkbox-question": CheckboxQuestion;
        "radio-question": RadioQuestion;
        "survey-component": SurveyComponent;
        "text-question": TextQuestion;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "checkbox-question": LocalJSX.CheckboxQuestion & JSXBase.HTMLAttributes<HTMLCheckboxQuestionElement>;
            "radio-question": LocalJSX.RadioQuestion & JSXBase.HTMLAttributes<HTMLRadioQuestionElement>;
            "survey-component": LocalJSX.SurveyComponent & JSXBase.HTMLAttributes<HTMLSurveyComponentElement>;
            "text-question": LocalJSX.TextQuestion & JSXBase.HTMLAttributes<HTMLTextQuestionElement>;
        }
    }
}
